### ISSUE TITLE
scx_layered: Fix crash on aarch64 due to unavailable cache id file

### ISSUE THREAD

**Issue by minosfuture** [sched-ext/scx#733]
`scx_layered` crashed on aarch64 because cache Id unavailable via `/sys/devices/system/cpu/cpu{}/cache/index{}/id`

```bash
04:03:05 [INFO] CPUs: online/possible=0/4 nr_cores=0
thread 'main' panicked at scheds/rust/scx_layered/src/main.rs:1049:34:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c2f74c3f928aeb503f15b4e9ef5778e77f3058b8/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/c2f74c3f928aeb503f15b4e9ef5778e77f3058b8/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_bounds_check
             at /rustc/c2f74c3f928aeb503f15b4e9ef5778e77f3058b8/library/core/src/panicking.rs:276:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/c2f74c3f928aeb503f15b4e9ef5778e77f3058b8/library/core/src/slice/index.rs:302:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/c2f74c3f928aeb503f15b4e9ef5778e77f3058b8/library/core/src/slice/index.rs:16:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/c2f74c3f928aeb503f15b4e9ef5778e77f3058b8/library/alloc/src/vec/mod.rs:2924:9
   6: scx_layered::CpuPool::new
             at ./scheds/rust/scx_layered/src/main.rs:1049:34
   7: scx_layered::Scheduler::init
             at ./scheds/rust/scx_layered/src/main.rs:1853:24
   8: scx_layered::main
             at ./scheds/rust/scx_layered/src/main.rs:2311:25
   9: core::ops::function::FnOnce::call_once
             at /rustc/c2f74c3f928aeb503f15b4e9ef5778e77f3058b8/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by minosfuture** [comment]
hi @hodgesds, how about using `/sys/devices/system/cpu/cpu*/topology` to get cpu topology (physical vs. logical cores), instead of using L2 cache vs. CPU mapping?

**Comment by hodgesds** [comment]
I think that is sort of along the lines of what #721 is describing as well. If we have a generic way to share this across all schedulers it will be really useful. What type of hardware are you using for testing on aarch64?

**Comment by minosfuture** [comment]
I'll give it a try. I'm actually running a VM on Mac M3.

**Comment by minosfuture** [comment]
Fixing this issue first in the PR attached. I can work on general topology utils in another PR.
Please review, thanks!
